Update variables.yml

diff --git a/.github/workflows/variables.yml b/.github/workflows/variables.yml
--- a/.github/workflows/variables.yml
+++ b/.github/workflows/variables.yml
@@ -1,20 +1,30 @@
 name: demo of variables and context
 
-on:   workflow_dispatch
+on:  
+  workflow_dispatch:
+    inputs:
+      should_fail:
+        description: "shall fail if input < 7"
+        required: true
+        type: int
+        default: '0'
 
 
 jobs:
   build-project:
     runs-on: ubuntu-latest
-    steps:
-          
+    steps: 
+      - name: steps that can fail
+        run: |
+          echo "failcheck..."
+          input_value=$(expr "${{ github.event.inputs.should_fail }}" + 0)
+          if [ "$input_value" -lt 7 ]; then
+            exit 1
+          fi
       - uses: actions/checkout@v4
-
       - name: Build project
         run: dotnet build
-
       - name: Get GitHub context info
         run: echo "${{ toJSON(github) }}"
-
       - name: Get repository name
         run: echo "${{ github.repository }}" 
